### PR TITLE
Asynchronously install packages

### PR DESCRIPTION
**Pull request by KristofferC**
I moved (and changed) the printing a bit because printing inside a task can get pretty confusing.

Build on top of https://github.com/StefanKarpinski/Pkg3.jl/pull/15.

The commit to look at is https://github.com/StefanKarpinski/Pkg3.jl/pull/25/commits/26983596f51b965c069b9ab020ecd479fbc73425.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
When you internalize, did you make a commit where the three (and thus its hash) is identical to the upstream version? If changes need to be made after that, they can be, but this is helpful for tracking what version we got the code from upstream.

**Comment by KristofferC** [comment]
IIRC, I cloned it, deleted `.git`-folder and then `git add`ed it, then commit. I can do it some other way if that is better.

**Comment by StefanKarpinski** [comment]
No, that's exactly how I did it too.

**Comment by KristofferC** [comment]
Simon tested and there are some problems on Windows. I'm fixing a VM now so I can check it out.

**Comment by StefanKarpinski** [comment]
FWIW, I haven't tested at all on Windows, so it may not be the fault of this PR. You may want to test on master first to make sure that works.

**Comment by KristofferC** [comment]
It was this PR. I think I fixed it though. The solution was to use as little of BinaryProvider as possible :P. It works reliably on my VM now but let's wait for Simon to check it as well.

**Comment by SimonDanisch** [comment]
But shouldn't we fix that in BinaryProvider as well then?

**Comment by KristofferC** [comment]
Feel free to fix it :)

**Comment by SimonDanisch** [comment]
got me there :P I guess we should at least ping @keno and @staticfloat, or are they already aware of that issue?

Btw, the latest commit fixed it on my machine as well :)

**Comment by staticfloat** [comment]
What issue are you seeing?

**Comment by KristofferC** [comment]
Deadlocks on Windows when starting a bunch of tasks that download and unpack files using the `download` and `unpack` commands in BinaryProvider. Quite difficult to debug because print statements in different positions seemed to make it work again.

The consumer at https://github.com/StefanKarpinski/Pkg3.jl/pull/25/commits/760ceca113431f4514fd131c2140059eb6e9769f#diff-920ed338dcbd9d62489c6d12dc2fbb18R386 waits for the `put!´ at https://github.com/StefanKarpinski/Pkg3.jl/pull/25/commits/760ceca113431f4514fd131c2140059eb6e9769f#diff-920ed338dcbd9d62489c6d12dc2fbb18R375 which never arrives.

It did seem that usually it was the first task that started that never finishes.

**Comment by KristofferC** [comment]
Since this works for Simon now, perhaps we should try it out on master, barring any requests from review.

**Pull request merged**
